version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    restart: always
    ports:
      - '3000:3000'

  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: arcs-material
    ports:
      - '8080:8080'
